[global]
   # Basics
   server string = nas
   workgroup = WORKGROUP
   server role = standalone server

   # The Problem: "Usershares" is a feature meant for desktop Linux environments (like Ubuntu Desktop) allowing non-root users to share folders out of their home directories on the fly. Because your M.2 drives are likely mounted system-wide and defined manually in /etc/samba/smb.conf, Samba's background service is getting confused. It's constantly scanning that system directory, failing to check the status (stat) of those shares due to a permissions mismatch, and locking up the I/O thread.
   usershare max shares = 0
   
   # NETWORK PERFORMANCE (The Secret Sauce)
   server multi channel support = yes
   # Force Samba to use all interfaces (maybe it's causing problem and not the best practice)
   # interfaces = 0.0.0.0/0
   # bind interfaces only = no
   # Samba's mDNS module can get confused about which IP address to anchor to when wildcards are used alongside Docker bridges (which I see you have running: docker0, br-71af39fe7).
   interfaces = 127.0.0.1 192.168.88.0/24
   bind interfaces only = yes
   
   # macOS Optimizations (vfs_fruit)
   vfs objects = catia fruit streams_xattr
   fruit:metadata = stream
   fruit:model = MacPro7,1@ECOLOR=226,226,224
   fruit:posix_rename = yes
   fruit:veto_appledouble = no
   fruit:nfs_aces = no
   fruit:wipe_intentionally_left_blank_rfork = yes
   fruit:delete_empty_adfiles = yes
   
   # Performance Tuning
   # Prevent Samba from scanning the directory to match upper/lower case
   case sensitive = true

   # Disable strict locking so files don't wait on unnecessary lock checks
   strict locking = no

   # Optimize buffers for modern high-speed networks
   min receivefile size = 16384
   socket options = TCP_NODELAY IPTOS_LOWDELAY
   use sendfile = yes

   # Enable asynchronous I/O to handle multiple files concurrently
   aio read size = 1
   aio write size = 1
   server signing = disabled
   server min protocol = SMB2_02
   smb2 leases = yes
   # Ensure no "mandatory" flags are lurking
   # The Problem: This parameter is deprecated and completely removed in modern versions of Samba (like the 4.19.x version you are running).
   # smb2 security mode = 0x01

   # Security (Optional but good)
   map to guest = Bad User

   # MacOS mDNS issue
   # handle the Mac's hostname quirks and stop the strict DFS verification
   host msdfs = no
   mdns name = mdns

[NasShare]
   # Point this to the MERGERFS pool, not the individual disks
   path = /mnt/nas_pool
   browsable = yes
   writable = yes
   guest ok = no
   force user = @nas
   # These enforce permissions so you can edit files created by Docker
   force create mode = 0775
   force directory mode = 0775
